//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Role { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Values { get; set; }
        public int System { get; set; }
    
        public virtual Systems Systems { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Types Types { get; set; }
    }
}
